using System.Collections.Generic;

public static class NPCEventData
{

    public static readonly List<string> Complaints = new List<string>
    {
        "Hay ra dẻ quá à!",
        "Làm quá nó ô dề.",
        "Còn cái nịt.",
        "Kiếp nạn thứ 82.",
        "Tự nhiên cái...",
        "U mê không lối thoát.",
        "Xin vía.",
        "Tới công chuyện.",
        "Ủa alo?",
        "Ủa gì vậy trời?",
        "Ủa rồi luôn á?",
        "Cook.",
        "Flop rồi.",
        "Hết cứu.",
        "Toang.",
        "Quá trời quá đất.",
        "Đúng nhận sai cãi.",
        "Có cái gì đó sai sai.",
        "Ai hỏi?",
        "Đừng có làm quá.",
        "Đỉnh nóc, kịch trần.",
        "Sống vậy ai chơi.",
        "Khó vậy cũng nghĩ ra.",
        "Không ai làm lại.",
        "Xin phép bất lực.",
        "Thôi em chịu.",
        "Khum nha.",
        "Quá dữ luôn.",
        "Mắc cái giống gì vậy?",
        "Đừng hề nữa.",
        "Nghe mà hết hồn.",
        "Có cần vậy không?",
        "Đúng là hết nước chấm.",
        "Quá là uy tín.",
        "Ổn áp.",
        "Mượt như Sunsilk.",
        "Hợp lý chưa?",
        "Đúng bài luôn.",
        "Có miếng.",
        "Cháy quá.",
        "Mượt dữ.",
        "Không phải dạng vừa đâu.",
        "Ghê chưa ghê chưa.",
        "Quá là tín.",
        "Được của nó.",
        "Đỉnh của chóp.",
        "Căng cực.",
        "Bất ổn quá.",
        "Căng như dây đàn.",
        "Lag quá.",
        "Ping 999+",
        "Bug nữa hả?",
        "Đồ án lại báo.",
        "Deadline dí.",
        "Mai tính.",
        "Mai làm.",
        "Ngủ cái đã.",
        "Cho em thở cái.",
        "Đói ngang.",
        "Trà sữa cứu em.",
        "Cafe không?",
        "Hết tiền thật.",
        "Qua môn là được.",
        "Đừng gọi em.",
        "Trời ơi cứu tui",
        "Em vô can.",
        "Cho xin cái hint.",
        "Có AI làm hộ không?",
        "Đời không như là mơ.",
        "Ủa thiệt hả?",
        "Không tin nổi luôn.",
        "Cười xỉu.",
        "Cười ngang.",
        "Muốn xỉu ngang.",
        "Sốc tâm lý.",
        "Não em offline.",
        "Server lag rồi.",
        "Thôi mình về.",
        "Chịu luôn.",
        "Tự nhiên thấy mệt.",
        "Có gì đó không đúng.",
        "Ủa xong luôn?",
        "Em muốn về nhà.",
        "Xin một vé bình yên.",
        "Em ổn... chắc vậy.",
        "Làm người khó quá."
    };

}
